# Generated by Django 2.1.7 on 2019-04-05 09:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sharif', '0002_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
