# Generated by Django 2.1.7 on 2019-04-05 10:00

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_sharif', '0003_auto_20190405_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='content',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='content',
        ),
        migrations.AlterField(
            model_name='grid',
            name='description',
            field=froala_editor.fields.FroalaField(null='True'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='title',
            field=froala_editor.fields.FroalaField(null='True'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=froala_editor.fields.FroalaField(null='True'),
        ),
    ]
