# Generated by Django 2.1.7 on 2019-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sharif', '0004_auto_20190405_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='active',
            field=models.BooleanField(default='True'),
        ),
    ]
