# Generated by Django 2.1.7 on 2019-04-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sharif', '0010_auto_20190405_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grid',
            new_name='post',
        ),
    ]
